### ISSUE TITLE
Logo broken in the Organization readme

### ISSUE THREAD

**Issue by m-linner-ericsson** [eiffel-community/.github#17]
### Description
The logo on the organization readme does not work as can be seen on https://github.com/eiffel-community

### Motivation
Bad experience for the visitor

### Exemplification
N/A

### Benefits
Broken images are not a good sign

### Possible Drawbacks
None

**Comment by magnusbaeck** [comment]
The image URL used is https://github.com/eiffel-community/.github/raw/images/eiffel-logo.png but it should probably be https://raw.githubusercontent.com/eiffel-community/.github/master/images/eiffel-logo.png.
