### ISSUE TITLE
A question about the copyright notice

### ISSUE THREAD

**Issue by t-persson** [eiffel-community/.github#5]
### Description
There is currently a Copyright message at the top of the raw CONTRIBUTING.md file.
Should it be there?

### Motivation
Just a question :)

**Comment by t-persson** [comment]
@henning-roos

**Comment by henning-roos** [comment]
I don't really know, but probably not. It is a legacy from the eiffel-repository-template. I agree that it is a bit strange. We should probably remove it.
@d-stahl-ericsson, since you created the original CONTRIBUTING.md file I copied, do you have any arguments why to keep it?
